### Health
GET http://localhost:5000/health


### Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com", 
    "password": "password123"
}

### Login user
POST http://localhost:5000/auth/login 
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password123"
}


### Create an account
POST http://localhost:5000/accounts
Content-Type: application/json

{
  "userId": "15ab9391-78d1-4cb3-b262-d8f0919b16f7",
  "currency": "USD"
}

### View all accounts
GET http://localhost:5000/accounts/15ab9391-78d1-4cb3-b262-d8f0919b16f7

### add income
POST http://localhost:5000/transactions/income
Content-Type: application/json

{
  "accountId": "ea15c393-4e95-428f-9c5b-2e0380bfa7dd",
  "amount": 5000
}

### add expense
POST http://localhost:5000/transactions/expense
Content-Type: application/json

{
  "accountId": "ea15c393-4e95-428f-9c5b-2e0380bfa7dd",
  "amount": 300
}