### Health
GET http://localhost:5000/health


### Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com", 
    "password": "password123"
}

### Login user
POST http://localhost:5000/auth/login 
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password123"
}


### Create an account
POST http://localhost:5000/accounts
Content-Type: application/json

{
  "userId": "1bf869bf-5f53-4ceb-a25c-fd0bf2e50fd7",
  "currency": "EUR"
}

### View all accounts
GET http://localhost:5000/accounts/1bf869bf-5f53-4ceb-a25c-fd0bf2e50fd7

### add income
POST http://localhost:5000/transactions/income
Content-Type: application/json

{
  "accountId": "9d3683c6-06c5-4627-96e6-2d61a9b0e6a4",
  "amount": 1000
}

### add expense
POST http://localhost:5000/transactions/expense
Content-Type: application/json

{
  "accountId": "9d3683c6-06c5-4627-96e6-2d61a9b0e6a4",
  "amount": 100
}